routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Auth::routes();

Route::get('/home', function() {return view('home');
})->name('home')->middleware('auth');
Route::resource('users', \App\Http\Controllers\UserController::class)->middleware('auth');
Route::resource('obat', \App\Http\Controllers\ObatController::class)->middleware('auth');
Route::resource('distributor', \App\Http\Controllers\DistributorController::class)->middleware('auth');
Route::resource('penjualan', \App\Http\Controllers\PenjualanController::class)->middleware('auth');

app/Models/Obat.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;


class Obat extends Model
{
    use HasFactory;
    
    protected $table = 'obat';
    protected $fillable = [
    'kode_obat',
    'nama_obat',
    'merk',
    'jenis',
    'satuan',
    'golongan',
    'kemasan',
    'harga_jual',
    'stok'
    ];
}

app/Http/Controllers/ObatController.php
<?php

namespace App\Http\Controllers;

use App\Models\Obat;
use Illuminate\Http\Request;

class ObatController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $obat = Obat::all();
        return view('obat.index', [
        'obat' => $obat
        ]);
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        return view('obat.create');
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        $request->validate([
            'kode_obat' => 'required',
            'nama_obat' => 'required',
            'merk' => 'required',
            'jenis' => 'required',
            'satuan' => 'required',
            'golongan' => 'required',
            'kemasan' => 'required',
            'harga_jual' => 'required',
            'stok' => 'required'
            ]);
            $array = $request->only([
                'kode_obat',
                'nama_obat',
                'merk',
                'jenis',
                'satuan',
                'golongan',
                'kemasan',
                'harga_jual',
                'stok'
            ]);
            $obat = Obat::create($array);
            return redirect()->route('obat.index')
            ->with('success_message', 'Berhasil menambah obat
            baru');
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {
        $obat = Obat::find($id);
        if (!$obat) return redirect()->route('obat.index')->with('error_message', 'Obat dengan id = '.$id.' tidak ditemukan');
            return view('obat.edit', [
            'obat' => $obat
        ]);
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'kode_obat' => 'required',
            'nama_obat' => 'required',
            'merk' => 'required',
            'jenis' => 'required',
            'satuan' => 'required',
            'golongan' => 'required',
            'kemasan' => 'required',
            'harga_jual' => 'required',
            'stok' => 'required',
            ]);
            $obat = Obat::find($id);
            $obat->kode_obat = $request->kode_obat;
            $obat->nama_obat = $request->nama_obat;
            $obat->merk = $request->merk;
            $obat->jenis = $request->jenis;
            $obat->satuan = $request->satuan;
            $obat->golongan = $request->golongan;
            $obat->kemasan = $request->kemasan;
            $obat->harga_jual = $request->harga_jual;
            $obat->stok = $request->stok;
            $obat->save();
            return redirect()->route('obat.index')->with('success_message', 'Berhasil mengubah obat');
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        $obat = Obat::find($id);
        if ($obat) $obat->delete();return redirect()->route('obat.index')->with('success_message', 'Berhasil menghapus obat');
    }
}

resources/views/obat/create.blade.php
@extends('adminlte::page')
@section('title', 'Tambah Data Obat')
@section('content_header')
<h1 class="m-0 text-dark">Tambah Data Obat</h1>
@stop
@section('content')
<form action="{{route('obat.store')}}" method="post">
    @csrf
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <div class="form-group">
                        <label for="kode_obat">Kode Obat</label>
                        <input type="text" class="form-control 
@error('kode_obat') is-invalid @enderror" id="kode_obat" placeholder="Kode Obat" name="kode_obat" value="{{old('kode_obat')}}">
                        @error('kode_obat') <span class="text-danger">{{$message}}</span> @enderror
                    </div>

                    <div class="form-group">
                        <label for="nama_obat">Nama Obat</label>
                        <input type="text" class="form-control 
@error('nama_obat') is-invalid @enderror" id="nama_obat" placeholder="Nama Obat" name="nama_obat" value="{{old('nama_obat')}}">
                        @error('nama_obat') <span class="text-danger">{{$message}}</span> @enderror
                    </div>

                    <div class="form-group">
                        <label for="merk">Merk</label>
                        <input type="text" class="form-control 
@error('merk') is-invalid @enderror" id="merk" placeholder="Merk" name="merk" value="{{old('merk')}}">
                        @error('merk') <span class="text-danger">{{$message}}</span> @enderror
                    </div>

                    <div class="form-group">
                        <label for="jenis">Jenis</label>
                        <input type="text" class="form-control 
@error('jenis') is-invalid @enderror" id="jenis" placeholder="Jenis" name="jenis" value="{{old('jenis')}}">
                        @error('jenis') <span class="text-danger">{{$message}}</span> @enderror
                    </div>

                    <div class="form-group">
                        <label for="satuan">Satuan</label>
                        <input type="text" class="form-control 
@error('satuan') is-invalid @enderror" id="satuan" placeholder="Satuan" name="satuan" value="{{old('satuan')}}">
                        @error('satuan') <span class="text-danger">{{$message}}</span> @enderror
                    </div>

                    <div class="form-group">
                        <label for="golongan">Golongan</label>
                        <input type="text" class="form-control 
@error('golongan') is-invalid @enderror" id="golongan" placeholder="Golongan" name="golongan" value="{{old('golongan')}}">
                        @error('golongan') <span class="text-danger">{{$message}}</span> @enderror
                    </div>

                    <div class="form-group">
                        <label for="kemasan">Kemasan</label>
                        <input type="text" class="form-control 
@error('kemasan') is-invalid @enderror" id="kemasan" placeholder="Kemasan" name="kemasan" value="{{old('kemasan')}}">
                        @error('kemasan') <span class="text-danger">{{$message}}</span> @enderror
                    </div>

                    <div class="form-group">
                        <label for="harga_jual">Harga Jual</label>
                        <input type="text" class="form-control 
@error('harga_jual') is-invalid @enderror" id="harga_jual" placeholder="Harga Jual" name="harga_jual" value="{{old('harga_jual')}}">
                        @error('harga_jual') <span class="text-danger">{{$message}}</span> @enderror
                    </div>

                    <div class="form-group">
                        <label for="stok">Stok</label>
                        <input type="text" class="form-control 
@error('stok') is-invalid @enderror" id="stok" placeholder="Stok" name="stok" value="{{old('stok')}}">
                        @error('stok') <span class="text-danger">{{$message}}</span> @enderror
                    </div>
                </div>
                <div class="card-footer">
                    <button type="submit" class="btn btn-primary">Simpan</button>
                    <a href="{{route('obat.index')}}" class="btn btn-default">
                        Batal
                    </a>
                </div>
            </div>
        </div>
    </div>
    @stop

resources/views/obat/edit.blade.php
@extends('adminlte::page')
@section('title', 'Edit Data Obat')
@section('content_header')
<h1 class="m-0 text-dark">Edit Data Obat</h1>
@stop
@section('content')
<form action="{{route('obat.update', $obat)}}" method="post">
    @method('PUT')
    @csrf
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">

                    <div class="form-group">
                        <label for="kode_obat">Kode Obat</label>
                        <input type="text" class="form-control 
@error('kode_obat') is-invalid @enderror" id="kode_obat" placeholder="Kode Obat" name="kode_obat" value="{{$obat->kode_obat ?? old('kode_obat')}}">
                        @error('kode_obat') <span class="text-danger">{{$message}}</span> @enderror
                    </div>

                    <div class="form-group">
                        <label for="nama_obat">Nama Obat</label>
                        <input type="text" class="form-control 
@error('nama_obat') is-invalid @enderror" id="nama_obat" placeholder="Nama Obat" name="nama_obat" value="{{$obat->nama_obat ?? old('nama_obat')}}">
                        @error('nama_obat') <span class="text-danger">{{$message}}</span> @enderror
                    </div>

                    <div class="form-group">
                        <label for="merk">Merk</label>
                        <input type="text" class="form-control 
@error('merk') is-invalid @enderror" id="merk" placeholder="Merk" name="merk" value="{{$obat->merk ?? old('merk')}}">
                        @error('merk') <span class="text-danger">{{$message}}</span> @enderror
                    </div>

                    <div class="form-group">
                        <label for="jenis">Jenis</label>
                        <input type="text" class="form-control 
@error('jenis') is-invalid @enderror" id="jenis" placeholder="Jenis" name="jenis" value="{{$obat->jenis ?? old('jenis')}}">
                        @error('jenis') <span class="text-danger">{{$message}}</span> @enderror
                    </div>

                    <div class="form-group">
                        <label for="satuan">Satuan</label>
                        <input type="text" class="form-control 
@error('satuan') is-invalid @enderror" id="satuan" placeholder="Satuan" name="satuan" value="{{$obat->satuan ?? old('satuan')}}">
                        @error('satuan') <span class="text-danger">{{$message}}</span> @enderror
                    </div>

                    <div class="form-group">
                        <label for="golongan">Golongan</label>
                        <input type="text" class="form-control 
@error('golongan') is-invalid @enderror" id="golongan" placeholder="Golongan" name="golongan" value="{{$obat->golongan ?? old('golongan')}}">
                        @error('golongan') <span class="text-danger">{{$message}}</span> @enderror
                    </div>

                    <div class="form-group">
                        <label for="kemasan">Kemasan</label>
                        <input type="text" class="form-control 
@error('kemasan') is-invalid @enderror" id="kemasan" placeholder="Kemasan" name="kemasan" value="{{$obat->kemasan ?? old('kemasan')}}">
                        @error('kemasan') <span class="text-danger">{{$message}}</span> @enderror
                    </div>

                    <div class="form-group">
                        <label for="harga_jual">Harga Jual</label>
                        <input type="text" class="form-control 
@error('harga_jual') is-invalid @enderror" id="harga_jual" placeholder="Harga Jual" name="harga_jual" value="{{$obat->harga_jual ?? old('harga_jual')}}">
                        @error('harga_jual') <span class="text-danger">{{$message}}</span> @enderror
                    </div>


                    <div class="form-group">
                        <label for="stok">Stok</label>
                        <input type="text" class="form-control 
@error('stok') is-invalid @enderror" id="stok" placeholder="Stok" name="stok" value="{{$obat->stok ?? old('stok')}}">
                        @error('stok') <span class="text-danger">{{$message}}</span> @enderror
                    </div>

                </div>
                <div class="card-footer">
                    <button type="submit" class="btn btn-primary">Simpan</button>
                    <a href="{{route('obat.index')}}" class="btn btn-default">
                        Batal
                    </a>
                </div>
            </div>
        </div>
    </div>
    @stop

resources/views/obat/index.blade.php
@extends('adminlte::page')
@section('title', 'List Obat')
@section('content_header')
<h1 class="m-0 text-dark">List Obat</h1>
@stop
@section('content')
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <a href="{{route('obat.create')}}" class="btn
btn-primary mb-2">
                    Tambah
                </a>
                <table class="table table-hover table-bordered
table-stripped" id="example2">
                    <thead>
                        <tr>
                            <th>No.</th>
                            <th>Kode Obat</th>
                            <th>Nama Obat</th>
                            <th>Merk</th>
                            <th>Jenis</th>
                            <th>Satuan</th>
                            <th>Golongan</th>
                            <th>Kemasan</th>
                            <th>Harga Jual</th>
                            <th>Stok</th>
                            <th>Opsi</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($obat as $key => $bs)
                        <tr>
                            <td>{{$key+1}}</td>
                            <td>{{$bs->kode_obat}}</td>
                            <td>{{$bs->nama_obat}}</td>
                            <td>{{$bs->merk}}</td>
                            <td>{{$bs->jenis}}</td>
                            <td>{{$bs->satuan}}</td>
                            <td>{{$bs->golongan}}</td>
                            <td>{{$bs->kemasan}}</td>
                            <td>{{$bs->harga_jual}}</td>
                            <td>{{$bs->stok}}</td>
                            <td>
                                <a href="{{route('obat.edit',
$bs)}}" class="btn btn-primary btn-xs">
                                    Edit
                                </a>
                                <a href="{{route('obat.destroy',
$bs)}}" onclick="notificationBeforeDelete(event, this)" class="btn btn-danger btn-xs">Delete
                                </a>
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
@stop
@push('js')
<form action="" id="delete-form" method="post">
    @method('delete')
    @csrf
</form>
<script>
$('#example2').DataTable({
    "responsive": true,
});

function notificationBeforeDelete(event, el) {
    event.preventDefault();
    if (confirm('Apakah anda yakin akan menghapus data ? ')) {
        $("#delete-form").attr('action', $(el).attr('href'));
        $("#delete-form").submit();
    }
}
</script>
@endpush