routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Auth::routes();

Route::get('/home', function() {return view('home');
})->name('home')->middleware('auth');
Route::resource('users', \App\Http\Controllers\UserController::class)->middleware('auth');
Route::resource('obat', \App\Http\Controllers\ObatController::class)->middleware('auth');
Route::resource('distributor', \App\Http\Controllers\DistributorController::class)->middleware('auth');
Route::resource('penjualan', \App\Http\Controllers\PenjualanController::class)->middleware('auth');

app/Models/Distributor.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Distributor extends Model
{
    use HasFactory;

    protected $table = 'distributor';
    protected $fillable = [
        'nama_distributor',
        'alamat',
        'notelepon'
        ];
}

app/Http/Controllers/DistributorController.php
<?php

namespace App\Http\Controllers;

use App\Models\Distributor;
use Illuminate\Http\Request;

class DistributorController extends Controller
{
    public function index()
    {
        $distributor = Distributor::all();
        return view('distributor.index', [
        'distributor' => $distributor
        ]);
    }

    public function create()
    {
        return view('distributor.create');
    }

    public function store(Request $request)
    {
        $request->validate([
            'nama_distributor' => 'required',
            'alamat' => 'required',
            'notelepon' => 'required'
            ]);
            $array = $request->only([
                'nama_distributor',
                'alamat',
                'notelepon'
            ]);
            $distributor = Distributor::create($array);
            return redirect()->route('distributor.index')
            ->with('success_message', 'Berhasil menambah distributor
            baru');
    }

    public function edit(string $id)
    {
        $distributor = Distributor::find($id);
        if (!$distributor) return redirect()->route('distributor.index')->with('error_message', 'Distributor dengan id = '.$id.' tidak ditemukan');
            return view('distributor.edit', [
            'distributor' => $distributor
        ]);
    }

    public function update(Request $request, $id)
    {
        $request->validate([
            'nama_distributor' => 'required',
            'alamat' => 'required',
            'notelepon' => 'required'
            ]);
            $distributor = Distributor::find($id);
            $distributor->nama_distributor = $request->nama_distributor;
            $distributor->alamat = $request->alamat;
            $distributor->notelepon = $request->notelepon;
            $distributor->save();
            return redirect()->route('distributor.index')->with('success_message', 'Berhasil mengubah distributor');
    }

    public function destroy(string $id)
    {
        $distributor = Distributor::find($id);
        if ($distributor) $distributor->delete();return redirect()->route('distributor.index')->with('success_message', 'Berhasil menghapus distributor');
    }
}

resources/views/distributor/create.blade.php
@extends('adminlte::page')
@section('title', 'Tambah Data Distributor')
@section('content_header')
<h1 class="m-0 text-dark">Tambah Data Distributor</h1>
@stop
@section('content')
<form action="{{route('distributor.store')}}" method="post">
    @csrf
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <div class="form-group">
                        <label for="nama_distributor">Nama Distributor</label>
                        <input type="text" class="form-control 
@error('nama_distributor') is-invalid @enderror" id="nama_distributor" placeholder="Nama Distributor" name="nama_distributor" value="{{old('nama_distributor')}}">
                        @error('nama_distributor') <span class="text-danger">{{$message}}</span> @enderror
                    </div>

                    <div class="form-group">
                        <label for="alamat">Alamat</label>
                        <input type="text" class="form-control 
@error('alamat') is-invalid @enderror" id="alamat" placeholder="Alamat" name="alamat" value="{{old('alamat')}}">
                        @error('alamat') <span class="text-danger">{{$message}}</span> @enderror
                    </div>

                    <div class="form-group">
                        <label for="notelepon">No Telepon</label>
                        <input type="text" class="form-control 
@error('notelepon') is-invalid @enderror" id="notelepon" placeholder="No Telepon" name="notelepon" value="{{old('notelepon')}}">
                        @error('notelepon') <span class="text-danger">{{$message}}</span> @enderror
                    </div>
                </div>
                <div class="card-footer">
                    <button type="submit" class="btn btn-primary">Simpan</button>
                    <a href="{{route('distributor.index')}}" class="btn btn-default">
                        Batal
                    </a>
                </div>
            </div>
        </div>
    </div>
    @stop

resources/views/distributor/edit.blade.php
@extends('adminlte::page')
@section('title', 'Edit Data Distributor')
@section('content_header')
<h1 class="m-0 text-dark">Edit Data Distributor</h1>
@stop
@section('content')
<form action="{{route('distributor.update', $distributor)}}" method="post">
    @method('PUT')
    @csrf
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">

                    <div class="form-group">
                        <label for="nama_distributor">Nama Distributor</label>
                        <input type="text" class="form-control 
@error('nama_distributor') is-invalid @enderror" id="nama_distributor" placeholder="Nama Distributor" name="nama_distributor" value="{{$distributor->nama_distributor ?? old('nama_distributor')}}">
                        @error('nama_distributor') <span class="text-danger">{{$message}}</span> @enderror
                    </div>

                    <div class="form-group">
                        <label for="alamat">Alamat</label>
                        <input type="text" class="form-control 
@error('alamat') is-invalid @enderror" id="alamat" placeholder="Alamat" name="alamat" value="{{$distributor->alamat ?? old('alamat')}}">
                        @error('alamat') <span class="text-danger">{{$message}}</span> @enderror
                    </div>

                    <div class="form-group">
                        <label for="notelepon">No Telepon</label>
                        <input type="text" class="form-control 
@error('notelepon') is-invalid @enderror" id="notelepon" placeholder="No Telepon" name="notelepon" value="{{$distributor->notelepon ?? old('notelepon')}}">
                        @error('notelepon') <span class="text-danger">{{$message}}</span> @enderror
                    </div>
                </div>
                <div class="card-footer">
                    <button type="submit" class="btn btn-primary">Simpan</button>
                    <a href="{{route('distributor.index')}}" class="btn btn-default">
                        Batal
                    </a>
                </div>
            </div>
        </div>
    </div>
    @stop

resources/views/distributor/index.blade.php
@extends('adminlte::page')
@section('title', 'List Distributor')
@section('content_header')
<h1 class="m-0 text-dark">List Distributor</h1>
@stop
@section('content')
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <a href="{{route('distributor.create')}}" class="btn
btn-primary mb-2">
                    Tambah
                </a>
                <table class="table table-hover table-bordered
table-stripped" id="example2">
                    <thead>
                        <tr>
                            <th>No.</th>
                            <th>Nama Distributor</th>
                            <th>Alamat</th>
                            <th>No Telepon</th>
                            <th>Opsi</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($distributor as $key => $bs)
                        <tr>
                            <td>{{$key+1}}</td>
                            <td>{{$bs->nama_distributor}}</td>
                            <td>{{$bs->alamat}}</td>
                            <td>{{$bs->notelepon}}</td>
                            <td>
                                <a href="{{route('distributor.edit',
$bs)}}" class="btn btn-primary btn-xs">
                                    Edit
                                </a>
                                <a href="{{route('distributor.destroy',
$bs)}}" onclick="notificationBeforeDelete(event, this)" class="btn btn-danger btn-xs">Delete
                                </a>
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
@stop
@push('js')
<form action="" id="delete-form" method="post">
    @method('delete')
    @csrf
</form>
<script>
$('#example2').DataTable({
    "responsive": true,
});

function notificationBeforeDelete(event, el) {
    event.preventDefault();
    if (confirm('Apakah anda yakin akan menghapus data ? ')) {
        $("#delete-form").attr('action', $(el).attr('href'));
        $("#delete-form").submit();
    }
}
</script>
@endpush